function  featureCValue = GetFeatureC(integralIm,x1, y1, x2, y2)
midPoint1 = round((x2-x1)/3)+x1;
midPoint2 = round((x2-x1)*(2/3))+x1;

point2      = integralIm(y2, midPoint1,:) - ...
              integralIm(y2, x1,:) - ...
              integralIm(y1,midPoint1,: ) + ...
              integralIm(y1 ,x1,:);
              
midPoint = integralIm(y2, midPoint2,:)   - ...
                        integralIm(y2, midPoint1,:) - ...
                        integralIm(y1, midPoint2,:) + ...
                        integralIm(y1, midPoint1,:);

point4      = integralIm(y2, x2,:) - ...
              integralIm(y2, midPoint2,:) - ...
              integralIm(y1, x2,:) + ...
                        integralIm(y1, midPoint2,:);    
featureCValue = midPoint - (point2 + point4);

